name: Build the Program

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_program:
    name: Build the Program
    runs-on: windows-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build the program
      run: dotnet publish -c Release -o build
      
    - name: Copy the essential files
      run: |
        cp -r Assets build
        cp -r Data build
        
    - name: Upload the build artifact
      uses: actions/upload-artifact@v3
      with:
        name: EdcHost-nightly-${{ github.ref_name }}-${{ github.sha }}
        path: build
        
  build_documentation:
    name: Build the Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Generate the documentation
        uses: mattnotmitt/doxygen-action@v1
        
      - name: Upload the page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: Docs/html
          
  deploy_documentation:
    name: Deploy the documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build_documentation
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the pages
        id: deployment
        uses: actions/deploy-pages@v1
