name: Build the Program

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_program:
    name: Build the Program
    runs-on: windows-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Replace the version strings
      run: sed -i 's/EDC_HOST_BUILD_REF/${{ github.ref_name }}/g' Source/*
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build the program
      run: dotnet publish -c Release -o build
      
    - name: Copy the essential files
      run: |
        cp -r Assets build
        cp Config.yml build
        
    - name: Upload the build artifact
      uses: actions/upload-artifact@v3
      with:
        name: EDC-Host-nightly-${{ github.sha }}
        path: build
